Lecture 2 notes

Read Clean code book for Python

First Topic:- Lambda expression

used mostly in pandas

In [6]:
f=lambda a:a**2
print(f(6))
# Short cut for the function
l=lambda a,b:a**b 
print(l(6,2))

36
36


Second Topic:-Map Expression

Transforms every single element in it

(any function,iterable)  iterable=datatype like list or set or etc

In [7]:
list(map(lambda x:x**2,[2,3,4,5]))#should be casted into list otherwise it will be a hexadecimal output

[4, 9, 16, 25]

task example

In [12]:
mylist=["aa","bb"]
list(map(lambda x:x.upper(),mylist))

['AA', 'BB']

Third Filter Function

the function in it should return true or false (conditional function) then creates a new list with the items that's accepted by the condition

In [4]:
mylist=[1,2,3,4,5,6,7,8,9,10]
list(filter(lambda x:x%3==0,mylist))

[3, 6, 9]

Brain storming problem

check if all the characters in the array are upper case or not

In [45]:
mylist=["AA","BB","CC"]
for i in mylist:
    if i.isupper():
        continue
    print(False)
    break
else:
    print(True)
#list(filter(lambda x:x%3==0,mylist))

True


In [3]:
myNewList=[]
myNewList=list(filter(lambda x:x%3==0,[3,5,6,7,8,9]))
print(myNewList)

[3, 6, 9]


Could be used in dictionary

Without Lambda

In [6]:
d={"D1":"AhmedAdel","D2":"CS"}
def myfun(x):
    return d[x].upper()
list(map(myfun,d))

['ahmedadel', 'cs']

Using lambda 

In [10]:
d={"D1":"AhmedAdel","D2":"CS"}
list(map(lambda x:d[x].upper(),d)) # d[x].upper use upper case for the values inside the key without it like this x.upper will upper case the keys only

['AHMEDADEL', 'CS']

List Comprehension

Returns List with whatever condition i give 

In [13]:
mylist=[i**2 for i in [1,2,3,4,5,6,7,8,9] if i%3==0]
print(mylist)

[9, 36, 81]


Do this i**2 for the variable i in the list[1,2,3,4,5,6,7,8,9] if this condition is true i%3==0

instead of this code

In [14]:
listnew=[1,2,3,4,5,6,7,8,9]
newlist=[]
for i in listnew:
    if i%3==0:
        newlist.append(i**2)
newlist
#They're both the same but less lines of code

[9, 36, 81]

Task

In [17]:
[i.upper() for i in ["ahmed Adel","hassan","ibrahim","mohammed","etc"]]

['AHMED ADEL', 'HASSAN', 'IBRAHIM', 'MOHAMMED', 'ETC']

In [20]:
listj=["apple bannana","mysql"]
[i.upper() for i in listj if i[0]=='a'] #or i.startswith('a')

['APPLE BANNANA']

How to do a Dynamic Function with unlimited variables

In [22]:
#Using arguments
def add(*args):
    return (sum(args))
add(3,2,4,5,6,2,1,3) #unlimited variables
#RETURNS A TUPLE

26

In [25]:
#OR KeyWord Arguments 
def fun(**kwargs):
    print(kwargs)#RETURNS ALL VALUES
    print(kwargs["K1"])#RETURNS A SPECIFIC VALUE
fun(K1="AHMED",K2="MOHAMMED") # returns a dictionary

{'K1': 'AHMED', 'K2': 'MOHAMMED'}
AHMED


Write Packing & Unpacking later

In [29]:
# Packing
def fun(x,y):
    return sum((x,y)),x*y
z=fun(2,3)
print(z) #returns a tuple with the sum and multiplication

(5, 6)


In [30]:
#Unpacking 
def fun(x,y):
    return sum((x,y)),x*y
z1,z2=fun(2,3)
print(z1)
print(z2)

5
6


Classes & Objects 

In [33]:
class person:
    height=3
    Weight=90

but this is not how things are going with python like we used to in c++ or java

instead we use the constructors

In [53]:
class person:
    def __init__(self,h,w):#self is like this we used before to refer that every object has its specific values
        self.height=h
        self.weight=w

In [90]:
ahmed=person() #object called ahmed from the class
ahmed.weight=75

NameError: name 'person' is not defined

Inheritance in Classes

In [59]:
class female(person):
    def __init__(self,h,w,colour):
        super().__init__(h,w)
        self.colour=colour

In [58]:
mona=female(175,75,"Black")
print(mona.height, mona.weight, mona.colour)

175 75 Black


In [52]:
class person:
    def __init__(self, h, w):
        self.height = h
        self.weight = w

class female(person):
    def __init__(self, h, w, colour):
        super().__init__(h, w)  # Call the parent class constructor with 2 arguments
        self.colour = colour

# Creating an instance of the female class
mona = female(175, 75, "Black")
print(mona.height, mona.weight, mona.colour)


175 75 Black


#################################################################

How to Create Your Own library to save some functions in it

create a python file and save it in the same place you saved the jupiter notebook file then import it inside your jupiter notebook

In [14]:
import cal as ahmed #file called cal.py
ahmed.add(2,3) #we can use as ahmed or without using as with the name cal

5

Numpy Library

In [15]:
import numpy as np

In [22]:
np.array([1,3,4,5,6])
# create numpy array

array([1, 3, 4, 5, 6])

In [21]:
np.arange(2,30,7)
#from 2 to 30 with 7 steps each

array([ 2,  9, 16, 23])

In [25]:
np.eye(3)
#3X3 array with a ones along a diagonal shape

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(3).shape

(3, 3)

In [23]:
np.arange(2,30,7).shape 
#linear so only number of rows will appear

(4,)

In [29]:
np.ones((3,6)) #array full of ones with 3X6 dimension 3 rows 6 columns

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [30]:
np.zeros((3,6)) #array full of zeros with 3X6 dimension 3 rows 6 columns

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [35]:
arr=np.random.rand(4,5) #array full of random values with dimension 4X5
arr

array([[0.55667134, 0.59172757, 0.55251866, 0.71826275, 0.66496818],
       [0.29954453, 0.30965077, 0.45193546, 0.72312393, 0.30240432],
       [0.489325  , 0.84361586, 0.33897366, 0.84159434, 0.82487386],
       [0.83362365, 0.35660217, 0.72199862, 0.62629178, 0.05472302]])

In [36]:
arr[:,:] #give me all the array

array([[0.55667134, 0.59172757, 0.55251866, 0.71826275, 0.66496818],
       [0.29954453, 0.30965077, 0.45193546, 0.72312393, 0.30240432],
       [0.489325  , 0.84361586, 0.33897366, 0.84159434, 0.82487386],
       [0.83362365, 0.35660217, 0.72199862, 0.62629178, 0.05472302]])

In [41]:
arr[0,:] #give me the 1st row and all the columns of the array

array([0.55667134, 0.59172757, 0.55251866, 0.71826275, 0.66496818])

In [42]:
arr[:,0:2] #give me all the rows and the columns from 0 to 1 note the end is 1 not 2

array([[0.55667134, 0.59172757],
       [0.29954453, 0.30965077],
       [0.489325  , 0.84361586],
       [0.83362365, 0.35660217]])

In [43]:
arr[:,[0,2,3]] #give me all the rows and specific columns 

array([[0.55667134, 0.55251866, 0.71826275],
       [0.29954453, 0.45193546, 0.72312393],
       [0.489325  , 0.33897366, 0.84159434],
       [0.83362365, 0.72199862, 0.62629178]])

In [44]:
arr[:,-1] #give me the last column

array([0.66496818, 0.30240432, 0.82487386, 0.05472302])

axis 0 equal rows 
axis 1 equal coulumns

except for pandas


copy array talks the same value but not the same in the memmory


Try to know what is a quantile later & Percentile

We can Reshape the array

In [58]:
arr=np.arange(10)
arr=arr.reshape(2,5)
#This example is reshaped from linear to a 2X5 array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Or we can bring it back to its flat or linear shape

In [50]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

we can put a condition on the array

In [62]:
arr>5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]])

We can filter the array

In [63]:
arr[arr>5]

array([6, 7, 8, 9])

Anding

In [68]:
arr[(arr>5) & (arr<7)]

array([6])

Oring

In [67]:
arr[(arr>5) | (arr<7)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Transpose the array is reversing the dimensions

In [70]:
arr.transpose().transpose()

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

DotProduct vs Elementwise

Element Wise 

is the Normal Multiplication of the arrays

Dot Product

In [73]:
arr1=np.arange(4).reshape(2,2)
arr1

array([[0, 1],
       [2, 3]])

In [74]:
arr2=np.arange(4).reshape(2,2)
arr2

array([[0, 1],
       [2, 3]])

In [75]:
arr1.dot(arr2)
#[a,b]        [e,f]              [a*e+b*g,a*f+b*h]
#[c,d]    *   [g,h]        =     [c*e+d*g,c*f+d*h]
# That's Called Dot Product

array([[ 2,  3],
       [ 6, 11]])

Working with Mathematical Formulas

Meaning of Mean Square Error

Regression
How to know if the model is learning or not 
you give them part of the data with the answers 
and after learning you give him the other part without the answers 
then the model predicts and then we know the accuracy of the model
if the diff between y predict and original y is low then the accuracy is high and if its high then the accuracy is low 

1/n * summation of (array or vector with prediction - array or vector with original) squared 
this is called mean square error

Mean square formula example

In [89]:
actual_array=np.arange(1,4)
prediction_array=np.array([1,1,1])
error=(1/3) * np.sum(np.square(prediction_array-actual_array))
error

np.float64(1.6666666666666665)